modLoader="javafml"
loaderVersion="[45,)"
license="LGPL-3.0-only"
issueTrackerURL="https://github.com/ErikEdits/JustQuests/issues"

[[mods]]
modId="justquests"
version="${file.jarVersion}"
displayName="JustQuests"
authors="ErikEdits"
description='''A lightweight, datapack-driven quest book for Forge.'''
logoFile="icon.png"

[[dependencies.justquests]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.justquests]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.19.5)"
    ordering="NONE"
    side="BOTH"
