REWARDS = {
    "format": 1,
    "notes": "value = value units per item (≈ minutes of average play). tier = content tier of the reward "
             "(reward tier <= quest tier + 1). family = never given for quests of the same family.",
    "items": [
        {"id": "minecraft:coal", "value": 0.25, "tier": 0, "max": 32, "family": "coal"},
        {"id": "minecraft:bread", "value": 0.45, "tier": 0, "max": 16, "family": "baking"},
        {"id": "minecraft:cooked_beef", "value": 0.5, "tier": 0, "max": 16, "family": "livestock"},
        {"id": "minecraft:cooked_porkchop", "value": 0.5, "tier": 0, "max": 16, "family": "livestock"},
        {"id": "minecraft:baked_potato", "value": 0.25, "tier": 0, "max": 32, "family": "crops"},
        {"id": "minecraft:apple", "value": 0.4, "tier": 0, "max": 8, "family": "fruit"},
        {"id": "minecraft:arrow", "value": 0.15, "tier": 0, "max": 32, "family": "archery"},
        {"id": "minecraft:torch", "value": 0.07, "tier": 0, "max": 32, "family": "lighting"},
        {"id": "minecraft:bone_meal", "value": 0.1, "tier": 0, "max": 32, "family": "undead"},
        {"id": "minecraft:oak_sapling", "value": 0.15, "tier": 0, "max": 16, "family": "forestry"},
        {"id": "minecraft:leather", "value": 0.4, "tier": 0, "max": 16, "family": "livestock"},
        {"id": "minecraft:string", "value": 0.4, "tier": 0, "max": 16, "family": "arthropods"},
        {"id": "minecraft:paper", "value": 0.12, "tier": 0, "max": 32, "family": "library"},
        {"id": "minecraft:book", "value": 1.2, "tier": 0, "max": 8, "family": "library"},
        {"id": "minecraft:cake", "value": 3.0, "tier": 0, "max": 1, "stack": 1, "family": "baking"},
        {"id": "minecraft:pumpkin_pie", "value": 1.0, "tier": 0, "max": 8, "family": "fruit"},
        {"id": "minecraft:cookie", "value": 0.12, "tier": 0, "max": 32, "family": "baking"},
        {"id": "minecraft:hay_block", "value": 1.4, "tier": 0, "max": 8, "family": "crops"},
        {"id": "minecraft:saddle", "value": 6.0, "tier": 0, "max": 1, "stack": 1, "family": "horses", "weight": 0.5},
        {"id": "minecraft:tnt", "value": 2.5, "tier": 0, "max": 4, "family": "monsters", "minDifficulty": "normal"},
        {"id": "minecraft:copper_ingot", "value": 0.15, "tier": 1, "max": 32, "family": "metals"},
        {"id": "minecraft:iron_ingot", "value": 0.6, "tier": 1, "max": 24, "family": "metals"},
        {"id": "minecraft:gold_ingot", "value": 1.3, "tier": 1, "max": 16, "family": "metals"},
        {"id": "minecraft:emerald", "value": 2.5, "tier": 1, "max": 16, "family": "gems"},
        {"id": "minecraft:lapis_lazuli", "value": 0.2, "tier": 1, "max": 32, "family": "gems"},
        {"id": "minecraft:redstone", "value": 0.2, "tier": 1, "max": 32, "family": "redstone"},
        {"id": "minecraft:amethyst_shard", "value": 0.35, "tier": 1, "max": 16, "family": "amethyst"},
        {"id": "minecraft:experience_bottle", "value": 1.2, "tier": 1, "max": 16, "family": "xp"},
        {"id": "minecraft:slime_ball", "value": 1.5, "tier": 1, "max": 8, "family": "monsters"},
        {"id": "minecraft:name_tag", "value": 8.0, "tier": 1, "max": 1, "family": "treasure", "weight": 0.4},
        {"id": "minecraft:lantern", "value": 0.8, "tier": 1, "max": 8, "family": "lighting"},
        {"id": "minecraft:bucket", "value": 1.6, "tier": 1, "max": 1, "stack": 16, "family": "iron_works"},
        {"id": "minecraft:shield", "value": 1.2, "tier": 1, "max": 1, "stack": 1, "family": "iron_tools"},
        {"id": "minecraft:iron_pickaxe", "value": 1.8, "tier": 1, "max": 1, "stack": 1, "family": "iron_tools"},
        {"id": "minecraft:spyglass", "value": 2.0, "tier": 1, "max": 1, "stack": 1, "family": "copper_works"},
        {"id": "minecraft:glow_berries", "value": 0.25, "tier": 1, "max": 16, "family": "lush"},
        {"id": "minecraft:diamond", "value": 5.0, "tier": 2, "max": 8, "family": "gems"},
        {"id": "minecraft:obsidian", "value": 1.0, "tier": 2, "max": 16, "family": "obsidian"},
        {"id": "minecraft:golden_carrot", "value": 1.5, "tier": 2, "max": 16, "family": "golden_food"},
        {"id": "minecraft:golden_apple", "value": 9.0, "tier": 2, "max": 2, "family": "golden_food",
         "minDifficulty": "normal"},
        {"id": "minecraft:ender_pearl", "value": 2.5, "tier": 2, "max": 8, "stack": 16, "family": "monsters"},
        {"id": "minecraft:compass", "value": 2.4, "tier": 2, "max": 1, "family": "redstone"},
        {"id": "minecraft:clock", "value": 5.0, "tier": 2, "max": 1, "family": "redstone"},
        {"id": "minecraft:nautilus_shell", "value": 5.0, "tier": 2, "max": 2, "family": "ocean", "weight": 0.5},
        {"id": "minecraft:diamond_pickaxe", "value": 16.0, "tier": 2, "max": 1, "stack": 1, "family": "diamond_gear",
         "minDifficulty": "hard"},
        {"id": "minecraft:quartz", "value": 0.3, "tier": 3, "max": 32, "family": "nether_ores"},
        {"id": "minecraft:glowstone_dust", "value": 0.25, "tier": 3, "max": 32, "family": "nether_ores"},
        {"id": "minecraft:blaze_rod", "value": 1.8, "tier": 3, "max": 8, "family": "nether_mobs"},
        {"id": "minecraft:ghast_tear", "value": 4.0, "tier": 3, "max": 4, "family": "nether_mobs"},
        {"id": "minecraft:netherite_scrap", "value": 12.0, "tier": 3, "max": 1, "family": "nether_ores",
         "minDifficulty": "hard"},
        {"id": "minecraft:shulker_shell", "value": 5.0, "tier": 4, "max": 2, "family": "end_mobs",
         "minDifficulty": "hard"},
        {"id": "minecraft:ender_eye", "value": 4.0, "tier": 4, "max": 4, "family": "end_prep"},
        {"id": "minecraft:cooked_chicken", "value": 0.5, "tier": 0, "max": 16, "family": "livestock"},
        {"id": "minecraft:cooked_salmon", "value": 0.9, "tier": 0, "max": 16, "family": "fishing"},
        {"id": "minecraft:honey_bottle", "value": 1.2, "tier": 0, "max": 8, "stack": 16, "family": "bees"},
        {"id": "minecraft:honeycomb", "value": 1.0, "tier": 0, "max": 8, "family": "bees"},
        {"id": "minecraft:lead", "value": 1.8, "tier": 1, "max": 2, "family": "transport"},
        {"id": "minecraft:campfire", "value": 0.5, "tier": 0, "max": 4, "family": "lighting"},
        {"id": "minecraft:bookshelf", "value": 4.5, "tier": 0, "max": 4, "family": "library"},
        {"id": "minecraft:crossbow", "value": 2.2, "tier": 1, "max": 1, "stack": 1, "family": "archery"},
        {"id": "minecraft:flint_and_steel", "value": 0.8, "tier": 1, "max": 1, "stack": 1, "family": "archery"},
        {"id": "minecraft:glow_ink_sac", "value": 1.0, "tier": 1, "max": 8, "family": "ocean"},
        {"id": "minecraft:iron_block", "value": 5.4, "tier": 1, "max": 2, "family": "metals", "minDifficulty": "normal"},
        {"id": "minecraft:lapis_block", "value": 1.8, "tier": 1, "max": 4, "family": "gems"},
        {"id": "minecraft:redstone_block", "value": 1.8, "tier": 1, "max": 4, "family": "redstone"},
        {"id": "minecraft:coal_block", "value": 2.3, "tier": 0, "max": 4, "family": "coal"},
        {"id": "minecraft:gold_block", "value": 11.7, "tier": 2, "max": 1, "family": "metals", "minDifficulty": "hard"},
        {"id": "minecraft:emerald_block", "value": 22.5, "tier": 2, "max": 1, "family": "gems", "minDifficulty": "hard"},
        {"id": "minecraft:powered_rail", "value": 1.6, "tier": 2, "max": 12, "family": "transport"},
        {"id": "minecraft:blaze_powder", "value": 0.9, "tier": 3, "max": 16, "family": "nether_mobs"},
        {"id": "minecraft:magma_cream", "value": 1.4, "tier": 3, "max": 8, "family": "nether_mobs"},
        {"id": "minecraft:phantom_membrane", "value": 3.0, "tier": 1, "max": 4, "family": "undead", "minDifficulty": "normal"},
        {"id": "minecraft:prismarine_crystals", "value": 1.5, "tier": 2, "max": 8, "family": "ocean"},
        {"id": "minecraft:sea_lantern", "value": 5.5, "tier": 2, "max": 2, "family": "ocean", "minDifficulty": "normal"},
        {"id": "minecraft:glistering_melon_slice", "value": 1.5, "tier": 2, "max": 8, "family": "brewing"},
        {"id": "minecraft:jukebox", "value": 5.5, "tier": 2, "max": 1, "family": "workstations"},
        {"id": "minecraft:music_disc_13", "value": 6.0, "tier": 1, "max": 1, "stack": 1, "family": "treasure", "weight": 0.3},
        {"id": "minecraft:music_disc_cat", "value": 6.0, "tier": 1, "max": 1, "stack": 1, "family": "treasure", "weight": 0.3},
        {"id": "minecraft:rabbit_foot", "value": 4.0, "tier": 0, "max": 2, "family": "wild_animals", "weight": 0.5},
        {"id": "minecraft:sugar", "value": 0.1, "tier": 0, "max": 32, "family": "plants"},
        {"id": "minecraft:white_wool", "value": 0.25, "tier": 0, "max": 32, "family": "wool"},
        {"id": "minecraft:glass", "value": 0.1, "tier": 0, "max": 32, "family": "glass"},
        {"id": "minecraft:mushroom_stew", "value": 2.0, "tier": 0, "max": 1, "stack": 1, "family": "mushrooms"},
    ],
    "effects": [
        {"id": "minecraft:speed", "valuePerMinute": 0.6, "minSeconds": 60, "maxSeconds": 480},
        {"id": "minecraft:haste", "valuePerMinute": 0.8, "minSeconds": 60, "maxSeconds": 480},
        {"id": "minecraft:night_vision", "valuePerMinute": 0.4, "minSeconds": 120, "maxSeconds": 600},
        {"id": "minecraft:water_breathing", "valuePerMinute": 0.5, "minSeconds": 120, "maxSeconds": 600},
        {"id": "minecraft:fire_resistance", "valuePerMinute": 0.7, "minSeconds": 60, "maxSeconds": 480},
        {"id": "minecraft:jump_boost", "valuePerMinute": 0.3, "minSeconds": 60, "maxSeconds": 300},
        {"id": "minecraft:resistance", "valuePerMinute": 1.0, "minSeconds": 60, "maxSeconds": 300,
         "minDifficulty": "hard"},
        {"id": "minecraft:luck", "valuePerMinute": 0.3, "minSeconds": 120, "maxSeconds": 600, "weight": 0.5},
        {"id": "minecraft:regeneration", "valuePerMinute": 3.0, "minSeconds": 30, "maxSeconds": 90, "minDifficulty": "hard"},
        {"id": "minecraft:slow_falling", "valuePerMinute": 0.4, "minSeconds": 60, "maxSeconds": 300},
        {"id": "minecraft:invisibility", "valuePerMinute": 0.5, "minSeconds": 60, "maxSeconds": 300},
        {"id": "minecraft:dolphins_grace", "valuePerMinute": 0.4, "minSeconds": 60, "maxSeconds": 300, "weight": 0.5},
        {"id": "minecraft:conduit_power", "valuePerMinute": 0.6, "minSeconds": 60, "maxSeconds": 300, "weight": 0.5},
    ],
    "lootTables": [
        {"id": "minecraft:chests/simple_dungeon", "value": 8.0, "tier": 1, "minDifficulty": "normal"},
        {"id": "minecraft:chests/abandoned_mineshaft", "value": 7.0, "tier": 1, "minDifficulty": "normal"},
        {"id": "minecraft:chests/village/village_weaponsmith", "value": 7.0, "tier": 1, "minDifficulty": "normal"},
        {"id": "minecraft:chests/desert_pyramid", "value": 9.0, "tier": 1, "minDifficulty": "hard"},
        {"id": "minecraft:chests/jungle_temple", "value": 9.0, "tier": 1, "minDifficulty": "hard"},
        {"id": "minecraft:chests/buried_treasure", "value": 14.0, "tier": 2, "minDifficulty": "hard"},
        {"id": "minecraft:chests/nether_bridge", "value": 12.0, "tier": 3, "minDifficulty": "hard"},
        {"id": "minecraft:chests/bastion_other", "value": 16.0, "tier": 3, "minDifficulty": "hard"},
        {"id": "minecraft:chests/end_city_treasure", "value": 18.0, "tier": 4, "minDifficulty": "hard"},
    ],
    "messages": [
        "The village thanks you!",
        "Word of your deeds spreads.",
        "Well done, adventurer.",
        "Another job well done.",
        "The quest board has a new hero.",
        "Someone will write songs about this.",
        "The traders are impressed.",
        "Good work. Rest a while.",
    ],
}

TEMPLATES = {
    "format": 1,
    "titles": {
        "collect_item": ["{Name} Haul", "{Name} Run", "Gather {Names}", "{Name} Stockpile", "{Name} Supply",
                         "{Name} Collector", "{Name} Pickup", "Bring {Names}",
                         "{Name} Delivery", "{Name} Gathering", "Need {Names}", "{Name} Bundle"],
        "mine_block": ["{Name} Miner", "Mine {Names}", "{Name} Dig", "{Name} Quarry", "Break {Names}",
                       "{Name} Excavation", "{Name} Shift", "{Name} Breaker", "Dig {Names}"],
        "craft_item": ["{Name} Order", "Craft {Names}", "{Name} Workshop", "{Name} Crafter", "Make {Names}",
                       "{Name} Commission", "{Name} Batch", "Build {Names}", "{Name} Request", "{Name} Assembly",
                       "{Name} Crafting"],
        "smelt_item": ["{Name} Supply", "Smelt {Names}", "{Name} Smeltery", "Hot {Names}", "{Name} Batch",
                       "Furnace: {Name}", "{Name} Heat", "Fire Up {Names}"],
        "kill_mob": ["{Name} Hunt", "{Name} Patrol", "Cull the {Names}", "{Name} Bounty", "{Name} Slayer",
                     "{Name} Trouble", "{Name} Cleanup", "{Name} Menace", "Stop the {Names}", "Hunt the {Names}",
                     "{Name} Watch"],
        "breed_animal": ["{Name} Breeder", "More {Names}", "{Name} Ranch", "{Name} Family", "Breed {Names}",
                         "{Name} Herd", "Baby {Names}", "{Name} Nursery", "{Name} Farm"],
        "tame_animal": ["New Friend", "Tame a {Name}", "{Name} Companion", "{Name} Whisperer", "Loyal {Name}", "{Name} Friend"],
        "consume_item": ["{Name} Feast", "Taste {Name}", "{Name} Tasting", "{Name} Snack", "{Name} Break", "{Name} Lunch", "Hungry for {Name}",
                         "{Name} Meal", "{Name} Supper"],
        "place_block": ["{Name} Builder", "Build with {Name}", "Place {Names}", "{Name} Project", "{Name} Works", "{Name} Layout", "Decorate: {Name}",
                        "{Name} Construction", "{Name} Design"],
        "visit_dimension": ["{Dimension} Trip", "Visit {Dimension}", "{Dimension} Journey", "Into {Dimension}",
                            "Gateway to {Dimension}", "{Dimension} Expedition"],
    },
    "phrases": {
        "collect_item": ["Collect {count} {names}", "Gather {count} {names}", "Pick up {count} {names}"],
        "mine_block": ["Mine {count} {names}", "Break {count} {names}"],
        "craft_item": ["Craft {count} {names}", "Make {count} {names}"],
        "smelt_item": ["Smelt {count} {names}"],
        "kill_mob": ["Defeat {count} {names}", "Hunt {count} {names}", "Slay {count} {names}"],
        "breed_animal": ["Breed {count} {names}"],
        "tame_animal": ["Tame {count} {names}"],
        "consume_item": ["Eat {count} {names}"],
        "place_block": ["Place {count} {names}", "Build with {count} {names}"],
        "visit_dimension": ["Travel to {dimension}", "Enter {dimension}"],
    },
    "variants": {
        "drink": {"phrases": ["Drink {count} {names}"], "titles": ["{Name} Break", "Taste {Name}", "{Name} Round"]},
        "cook": {"phrases": ["Cook {count} {names}"], "titles": ["Cook {Names}", "{Name} Batch", "Hot {Names}",
                                                               "{Name} Kitchen", "{Name} Order"]},
    },
    "fallbackTitles": ["{Name} Task", "{Name} Job", "{Name} Errand", "{Name} Duty", "{Name} Mission", "{Name} Work"],
    "comboTitles": ["{Family} Order", "{Family} Errand", "{Family} Job", "{Family} Supplies", "{Family} Duty",
                    "{Family} Chores"],
    "familyNames": {
        "wood": "Lumber", "forestry": "Forestry", "stone": "Quarry", "stonework": "Masonry", "sand": "Sand",
        "glass": "Glassworks", "soil": "Earthworks", "badlands": "Badlands", "lush": "Lush Cave", "snow": "Winter",
        "plants": "Gardening", "coal": "Coal", "metals": "Metal", "gems": "Gem", "redstone": "Redstone",
        "amethyst": "Amethyst", "obsidian": "Obsidian", "crops": "Farm", "fruit": "Orchard", "mushrooms": "Mushroom",
        "flowers": "Flower", "bees": "Beekeeping", "livestock": "Ranch", "wool": "Wool", "wild_animals": "Wildlife",
        "horses": "Stable", "pets": "Pet", "villagers": "Village", "fishing": "Fishing", "ocean": "Seafaring",
        "undead": "Undead", "arthropods": "Spider", "monsters": "Monster", "illagers": "Illager", "trial": "Trial",
        "lighting": "Lighting", "woodwork": "Carpentry", "baking": "Bakery", "library": "Library",
        "archery": "Fletcher", "iron_tools": "Toolsmith", "iron_armor": "Armorsmith", "iron_works": "Ironworks",
        "decor": "Decorator", "copper_works": "Copper", "golden_food": "Golden", "diamond_gear": "Diamond",
        "nether_travel": "Nether", "nether_blocks": "Nether Stone", "nether_ores": "Nether Mining",
        "nether_plants": "Nether Garden", "nether_mobs": "Nether Hunt", "end_travel": "End", "end_blocks": "End Stone",
        "end_plants": "Chorus", "end_mobs": "End Hunt", "end_prep": "Stronghold",
        "fd_crops": "Produce", "fd_wild": "Forager", "fd_straw": "Straw", "fd_tools": "Cutlery",
        "fd_kitchen": "Kitchen", "fd_furniture": "Cabinet", "fd_butchery": "Butcher", "fd_seafood": "Seafood",
        "fd_breakfast": "Breakfast", "fd_meals": "Sandwich", "fd_salads": "Salad", "fd_sweets": "Dessert",
        "fd_stews": "Stew", "fd_plates": "Dinner", "fd_drinks": "Drinks", "fd_feasts": "Feast", "fd_soil": "Compost",
        "fd_snacks": "Snack", "create_contraptions": "Contraption",
        "create_zinc": "Zinc", "create_stone": "Stone Layer", "create_masonry": "Masonry",
        "create_alloy": "Alloy", "create_kinetics": "Kinetics", "create_power": "Mill", "create_logistics": "Logistics",
        "create_machines": "Machine", "create_tools": "Engineer", "create_decor": "Seating", "create_sweets": "Treat",
        "create_quartz": "Rose Quartz",
        "deep_dark": "Deep Dark", "dyes": "Dye", "stone_tools": "Stonecutter", "leather_armor": "Leatherwork",
        "workstations": "Workshop", "transport": "Transport", "brewing": "Brewer", "exploration": "Explorer",
        "nether_animals": "Nether Ranch", "nether_crafts": "Nether Mason", "storage_blocks": "Treasury"
    },
    "tools": {
        "stone": "Needs a stone pickaxe or better",
        "iron": "Needs an iron pickaxe or better",
        "diamond": "Needs a diamond pickaxe",
        "netherite": "Needs a netherite pickaxe",
        "shears": "Use shears",
        "silk_touch": "Needs Silk Touch",
        "fishing_rod": "Use a fishing rod",
        "knife": "Use a Farmer's Delight knife",
        "shovel": "Use a shovel",
    },
    "hints": {
        "night": "They spawn at night and in dark caves.",
        "desert": "Look in deserts.",
        "swamp": "Look in swamps.",
        "jungle": "Look in jungles.",
        "taiga": "Look in taigas.",
        "snowy": "Look in snowy biomes.",
        "ocean": "Look in and near oceans.",
        "beach": "Look along beaches.",
        "savanna": "Look in savannas.",
        "badlands": "Look in badlands.",
        "mountains": "Look in the mountains.",
        "plains": "Common in plains.",
        "flower_forest": "Flower forests have the most.",
        "dark_forest": "Dark forests have plenty.",
        "mushroom_fields": "Look on mushroom islands.",
        "lush_caves": "Look in lush caves.",
        "dripstone_caves": "Look in dripstone caves.",
        "cherry_grove": "Look in cherry groves.",
        "mangrove_swamp": "Look in mangrove swamps.",
        "pale_garden": "Look in pale gardens.",
        "caves": "Found in caves.",
        "deep": "Found deep underground.",
        "geode": "Look inside amethyst geodes.",
        "village": "Villages often have them.",
        "farm": "Grow them on a farm.",
        "bees": "Needs bees and flowers.",
        "rare": "Rare, so take your time.",
        "river": "Look along rivers.",
        "fortress": "Found in Nether fortresses.",
        "bastion": "Found in bastion remnants.",
        "crimson_forest": "Found in crimson forests.",
        "warped_forest": "Found in warped forests.",
        "soul_sand_valley": "Found in soul sand valleys.",
        "basalt_deltas": "Found in basalt deltas.",
        "end_city": "Found in End cities.",
        "outer_islands": "Grows on the outer End islands.",
        "mineshaft": "Found in abandoned mineshafts.",
        "outpost": "Found at pillager outposts.",
        "monument": "Found at ocean monuments.",
        "trial_chambers": "Found in trial chambers.",
        "layers": "Found in thick stone layers underground.",
        "warm_ocean": "Look on coral reefs in warm oceans.",
        "ruined_portal": "Look around ruined portals.",
        "deep_dark": "Found in the deep dark.",
    },
    "sentences": {
        "tag": "Any {noun} counts.",
        "dimension": "Found in {dimension}.",
    },
    "dimensionNames": {
        "minecraft:overworld": "the Overworld",
        "minecraft:the_nether": "the Nether",
        "minecraft:the_end": "the End",
    },
}

THEMES = {
    "format": 1,
    "themes": [
        {"key": "blacksmith_order", "names": ["Blacksmith's Order", "Forge Work", "Smithy Supply"],
         "descriptions": ["The smithy needs help: {list}."],
         "slots": [{"types": ["smelt_item"], "keys": ["iron", "copper", "gold"]},
                   {"types": ["craft_item"], "families": ["iron_tools", "iron_works"]}]},
        {"key": "harvest_festival", "names": ["Harvest Festival", "Harvest Time", "Bumper Crop"],
         "descriptions": ["Bring in the harvest: {list}."],
         "slots": [{"types": ["collect_item"], "families": ["crops"]},
                   {"types": ["collect_item"], "families": ["crops"]},
                   {"types": ["collect_item"], "families": ["fruit"], "optional": True}]},
        {"key": "monster_patrol", "names": ["Monster Patrol", "Night Watch", "Undead Purge"],
         "descriptions": ["Keep the roads safe: {list}."],
         "slots": [{"types": ["kill_mob"], "families": ["undead"]},
                   {"types": ["kill_mob"], "families": ["undead", "arthropods"]},
                   {"types": ["kill_mob"], "families": ["monsters", "arthropods"], "optional": True}]},
        {"key": "ranch_hand", "names": ["Ranch Hand", "Farmyard Chores", "Barn Duty"],
         "descriptions": ["The ranch needs a hand: {list}."],
         "slots": [{"types": ["breed_animal"], "families": ["livestock", "wool"]},
                   {"types": ["breed_animal"], "families": ["livestock", "wool"]}]},
        {"key": "nether_expedition", "names": ["Nether Expedition", "Into the Fire", "Fortress Raid"],
         "descriptions": ["Bring back treasures from the Nether: {list}."],
         "slots": [{"types": ["mine_block", "collect_item"], "families": ["nether_ores"]},
                   {"types": ["collect_item", "kill_mob"], "families": ["nether_mobs"]},
                   {"types": ["visit_dimension"], "keys": ["nether_trip"], "optional": True}]},
        {"key": "mining_expedition", "names": ["Mining Expedition", "Deep Dig", "Cave Survey"],
         "descriptions": ["Head underground: {list}."],
         "slots": [{"types": ["mine_block"], "families": ["metals", "coal", "gems", "redstone"]},
                   {"types": ["mine_block", "collect_item"], "families": ["metals", "coal", "gems", "redstone", "stone"]}]},
        {"key": "lumberjack", "names": ["Lumberjack", "Timber!", "Woodcutter"],
         "descriptions": ["The sawmill is waiting: {list}."],
         "slots": [{"types": ["mine_block", "collect_item"], "families": ["wood"]},
                   {"types": ["place_block", "craft_item"], "families": ["forestry", "woodwork"]}]},
        {"key": "ocean_voyage", "names": ["Ocean Voyage", "Sea Harvest", "Tidal Work"],
         "descriptions": ["Head out to sea: {list}."],
         "slots": [{"types": ["collect_item"], "families": ["ocean", "fishing"]},
                   {"types": ["collect_item", "smelt_item", "kill_mob"], "families": ["ocean", "fishing"]}]},
        {"key": "camp_cook", "names": ["Camp Cook", "Campfire Dinner", "Supper Time"],
         "descriptions": ["Feed the camp: {list}."],
         "slots": [{"types": ["smelt_item"], "families": ["livestock", "wool", "fishing"]},
                   {"types": ["consume_item"], "families": ["livestock", "crops", "baking", "fishing"]}]},
        {"key": "builders_order", "names": ["Builder's Order", "Construction Job", "Masonry Work"],
         "descriptions": ["The builders need material: {list}."],
         "slots": [{"types": ["smelt_item", "craft_item"], "families": ["stone", "stonework", "glass"]},
                   {"types": ["place_block"], "families": ["stonework", "glass", "stone", "woodwork"]}]},
        {"key": "desert_trek", "names": ["Desert Trek", "Sand and Sun"],
         "descriptions": ["Brave the desert: {list}."],
         "slots": [{"types": ["collect_item", "mine_block", "smelt_item"], "keys": ["sand", "sandstone", "cactus"]},
                   {"types": ["kill_mob"], "keys": ["husks"]}]},
        {"key": "end_expedition", "names": ["End Expedition", "Beyond the Void"],
         "descriptions": ["Explore the End: {list}."],
         "minDifficulty": "hard",
         "slots": [{"types": ["mine_block", "collect_item"], "families": ["end_blocks", "end_plants"]},
                   {"types": ["kill_mob", "collect_item"], "families": ["end_mobs"]},
                   {"types": ["visit_dimension"], "keys": ["end_trip"], "optional": True}]},
        {"key": "beekeeper", "names": ["Beekeeper", "Busy Bees"],
         "descriptions": ["Tend the hives: {list}."],
         "slots": [{"types": ["collect_item", "breed_animal"], "keys": ["bees"]},
                   {"types": ["collect_item", "consume_item", "craft_item"], "keys": ["bees", "flowers"]}]},
        {"key": "winter_prep", "names": ["Winter Prep", "Cold Snap", "Snowbound"],
         "descriptions": ["Get ready for the cold: {list}."],
         "slots": [{"types": ["collect_item", "craft_item", "mine_block"], "families": ["snow"]},
                   {"types": ["collect_item", "breed_animal"], "families": ["wool"]}]},
        {"key": "tool_upgrade", "names": ["Tool Upgrade", "Iron Age", "Better Tools"],
         "descriptions": ["Time for better tools: {list}."],
         "slots": [{"types": ["smelt_item", "collect_item"], "keys": ["iron"]},
                   {"types": ["craft_item"], "families": ["iron_tools", "iron_armor"]}]},
        {"key": "railway_builder", "names": ["Railway Builder", "Rail Line", "Track Crew"],
         "descriptions": ["Lay down a new line: {list}."],
         "slots": [{"types": ["craft_item"], "keys": ["iron_works", "transport"]},
                   {"types": ["place_block"], "keys": ["iron_works"]}]},
        {"key": "redstone_workshop", "names": ["Redstone Workshop", "Circuit Builder"],
         "descriptions": ["Wire up the workshop: {list}."],
         "slots": [{"types": ["mine_block", "collect_item"], "keys": ["redstone", "deep_redstone"]},
                   {"types": ["craft_item"], "keys": ["redstone_parts", "redstone_gadgets"]}]},
        {"key": "enchanters_study", "names": ["Enchanter's Study", "Arcane Library"],
         "descriptions": ["The enchanter needs supplies: {list}."],
         "slots": [{"types": ["collect_item", "mine_block"], "keys": ["lapis", "deep_lapis"]},
                   {"types": ["craft_item"], "keys": ["library"]}]},
        {"key": "night_hunter", "names": ["Night Hunter", "Moonlit Hunt", "After Dark"],
         "descriptions": ["When the sun sets: {list}."],
         "slots": [{"types": ["kill_mob"], "families": ["arthropods", "monsters"]},
                   {"types": ["collect_item"], "families": ["arthropods", "monsters", "undead"]}]},
        {"key": "fishermans_day", "names": ["Fisherman's Day", "Catch of the Day", "Gone Fishing"],
         "descriptions": ["A day by the water: {list}."],
         "slots": [{"types": ["collect_item"], "families": ["fishing"]},
                   {"types": ["smelt_item", "consume_item"], "families": ["fishing"]}]},
        {"key": "florist", "names": ["Florist", "Flower Market", "Bouquet"],
         "descriptions": ["Fresh flowers for the market: {list}."],
         "slots": [{"types": ["collect_item"], "families": ["flowers"]},
                   {"types": ["collect_item"], "families": ["flowers"]},
                   {"types": ["craft_item"], "families": ["dyes"], "optional": True}]},
        {"key": "village_fair", "names": ["Village Fair", "Market Fair", "Harvest Market"],
         "descriptions": ["The fair opens soon: {list}."],
         "slots": [{"types": ["craft_item"], "families": ["baking"]},
                   {"types": ["breed_animal"], "families": ["livestock", "wool"]}]},
        {"key": "stonemason", "names": ["Stonemason", "Masonry Job", "Stone Works"],
         "descriptions": ["The stonemason needs help: {list}."],
         "slots": [{"types": ["mine_block", "collect_item"], "families": ["stone"]},
                   {"types": ["craft_item", "place_block", "smelt_item"], "families": ["stonework"]}]},
        {"key": "deep_dark_delve", "names": ["Deep Dark Delve", "Silent Depths"],
         "descriptions": ["Descend into the deep dark: {list}."],
         "minDifficulty": "hard",
         "slots": [{"types": ["mine_block"], "families": ["deep_dark"]},
                   {"types": ["mine_block"], "keys": ["deep_coal", "deep_copper", "deep_lapis", "deep_redstone", "diamond"]}]},
        {"key": "brewers_supplies", "names": ["Brewer's Supplies", "Potion Ingredients"],
         "descriptions": ["The brewer needs Nether goods: {list}."],
         "slots": [{"types": ["collect_item"], "keys": ["nether_wart"]},
                   {"types": ["collect_item", "craft_item", "kill_mob"], "keys": ["blazes", "magma_cubes", "nether_masonry"]}]},
        {"key": "leatherworker", "names": ["Leatherworker", "Tannery Order"],
         "descriptions": ["The tannery is busy: {list}."],
         "slots": [{"types": ["collect_item", "breed_animal"], "keys": ["cows", "rabbits"]},
                   {"types": ["craft_item"], "keys": ["leather_armor", "library", "decor"]}]},
        {"key": "copper_age", "names": ["Copper Age", "Copper Works"],
         "descriptions": ["Copper everywhere: {list}."],
         "slots": [{"types": ["mine_block", "collect_item", "smelt_item"], "keys": ["copper", "deep_copper"]},
                   {"types": ["craft_item", "place_block"], "keys": ["copper_blocks", "copper_works"]}]},
        {"key": "nether_builder", "names": ["Nether Builder", "Fortress Mason"],
         "descriptions": ["Build like the piglins: {list}."],
         "slots": [{"types": ["mine_block"], "families": ["nether_blocks"]},
                   {"types": ["craft_item", "smelt_item"], "keys": ["nether_masonry", "netherrack"]}]},
        {"key": "stable_hand", "names": ["Stable Hand", "Horse Ranch"],
         "descriptions": ["The stable needs work: {list}."],
         "slots": [{"types": ["breed_animal"], "keys": ["horses", "llamas", "camels"]},
                   {"types": ["craft_item"], "keys": ["wheat", "transport"]}]},
        {"key": "library_project", "names": ["Library Project", "Bookworm"],
         "descriptions": ["The librarian needs books: {list}."],
         "slots": [{"types": ["collect_item", "craft_item"], "keys": ["sugar_cane"]},
                   {"types": ["craft_item"], "keys": ["library"]}]},
        {"key": "lamplighter", "names": ["Lamplighter", "Lighthouse Keeper", "Bright Nights"],
         "descriptions": ["Light up the paths before dark: {list}."],
         "slots": [{"types": ["mine_block", "collect_item"], "keys": ["coal"]},
                   {"types": ["craft_item", "place_block"], "families": ["lighting"]}]},
        {"key": "glassblower", "names": ["Glassblower", "Glass Works", "Clear View"],
         "descriptions": ["The glassblower is out of sand: {list}."],
         "slots": [{"types": ["collect_item", "mine_block"], "keys": ["sand"]},
                   {"types": ["smelt_item", "craft_item", "place_block"], "keys": ["glass", "glass_more"]}]},
        {"key": "potter", "names": ["Potter's Wheel", "Clay Works", "Kiln Day"],
         "descriptions": ["The potter's kiln is waiting: {list}."],
         "slots": [{"types": ["collect_item", "mine_block"], "keys": ["clay", "clay_blocks"]},
                   {"types": ["smelt_item", "craft_item", "place_block"], "keys": ["bricks", "terracotta_art"]}]},
        {"key": "pet_shop", "names": ["Pet Shop", "Animal Friends", "Critter Care"],
         "descriptions": ["The pet shop needs new friends: {list}."],
         "slots": [{"types": ["tame_animal", "breed_animal"], "families": ["pets"]},
                   {"types": ["breed_animal"], "families": ["wild_animals"]}]},
        {"key": "mushroom_forager", "names": ["Mushroom Forager", "Fungus Hunt", "Spore Season"],
         "descriptions": ["The cook wants mushrooms: {list}."],
         "slots": [{"types": ["collect_item", "consume_item"], "keys": ["mushrooms"]},
                   {"types": ["mine_block"], "keys": ["mushroom_blocks"]}]},
        {"key": "cave_garden", "names": ["Cave Garden", "Lush Caves", "Green Below"],
         "descriptions": ["Something grows underground: {list}."],
         "slots": [{"types": ["mine_block"], "keys": ["moss"]},
                   {"types": ["collect_item", "consume_item"], "keys": ["glow_berries"]}]},
        {"key": "rock_collector", "names": ["Rock Collector", "Quarry Master", "Stone Survey"],
         "descriptions": ["The geologist wants samples: {list}."],
         "minDifficulty": "normal",
         "slots": [{"types": ["mine_block"], "keys": ["andesite", "granite", "diorite"]},
                   {"types": ["mine_block"], "keys": ["tuff", "calcite", "dripstone", "deepslate"]}]},
        {"key": "diamond_smith", "names": ["Diamond Smith", "Master Smith", "Sparkling Gear"],
         "descriptions": ["Only the best will do: {list}."],
         "minDifficulty": "hard",
         "slots": [{"types": ["mine_block", "collect_item"], "keys": ["diamond"]},
                   {"types": ["craft_item"], "families": ["diamond_gear"]}]},
        {"key": "bake_sale", "names": ["Bake Sale", "Sweet Tooth", "Market Stall"],
         "descriptions": ["The village bake sale needs you: {list}."],
         "slots": [{"types": ["craft_item", "consume_item"], "keys": ["baking", "food_crafts"]},
                   {"types": ["collect_item"], "families": ["fruit"]}]},
        {"key": "nether_gardener", "names": ["Nether Gardener", "Fungal Grove", "Crimson Harvest"],
         "descriptions": ["Even the Nether has a garden: {list}."],
         "minDifficulty": "hard",
         "slots": [{"types": ["collect_item", "mine_block"], "families": ["nether_plants"]},
                   {"types": ["collect_item", "mine_block"], "families": ["nether_plants"]}]},
        {"key": "camp_setup", "names": ["Camp Setup", "Base Camp", "Night Camp"],
         "descriptions": ["Set up camp before nightfall: {list}."],
         "slots": [{"types": ["mine_block", "collect_item"], "keys": ["logs_any", "oak_wood", "birch_wood", "spruce_wood"]},
                   {"types": ["craft_item"], "keys": ["campfires", "torches"]}]},
        {"key": "workshop_setup", "names": ["Workshop Setup", "New Workshop", "Crafting Corner"],
         "descriptions": ["Every village needs a workshop: {list}."],
         "slots": [{"types": ["craft_item"], "keys": ["workstations"]},
                   {"types": ["craft_item"], "keys": ["workstations"]},
                   {"types": ["craft_item"], "keys": ["workstations", "storage", "furnaces"], "optional": True}]},
        {"key": "adventurers_kit", "names": ["Adventurer's Kit", "Ready to Roam", "Travel Gear"],
         "descriptions": ["Pack for the road: {list}."],
         "slots": [{"types": ["craft_item"], "keys": ["iron_tools", "gear_misc"]},
                   {"types": ["craft_item"], "keys": ["iron_armor", "leather_armor", "transport"]}]},
        {"key": "treasure_hunter", "names": ["Treasure Hunter", "Deep Riches", "Gem Seeker"],
         "descriptions": ["Riches lie deep underground: {list}."],
         "minDifficulty": "hard",
         "slots": [{"types": ["mine_block", "collect_item"], "families": ["gems"]},
                   {"types": ["mine_block"], "families": ["obsidian"]}]},
    ],
}

BALANCE = {
    "format": 1,
    "notes": "All tunables. World overrides: <world>/justquests/generator_v2/balance.json is deep-merged over this file.",
    "difficulties": {
        "EASY": {"targetMinutes": [4, 10], "maxTier": 1, "objectiveWeights": [100, 0, 0], "rewardRate": 1.0,
                 "budgetClamp": [3, 15], "dimensionTravel": False, "effectChance": 0.0, "lootTableChance": 0.0,
                 "messageChance": 0.10, "claimExpiryHours": 0, "tierWeights": [1.0, 0.7, 0, 0, 0],
                 "typeWeights": {"place_block": 1.5, "tame_animal": 0.5}},
        "NORMAL": {"targetMinutes": [8, 20], "maxTier": 2, "objectiveWeights": [75, 25, 0], "rewardRate": 1.2,
                   "budgetClamp": [8, 30], "dimensionTravel": True, "effectChance": 0.05, "lootTableChance": 0.03,
                   "messageChance": 0.08, "claimExpiryHours": 0, "tierWeights": [0.7, 1.0, 0.8, 0.8, 0.6],
                   "typeWeights": {}},
        "HARD": {"targetMinutes": [15, 35], "maxTier": 4, "objectiveWeights": [50, 35, 15], "rewardRate": 1.5,
                 "budgetClamp": [18, 60], "dimensionTravel": True, "effectChance": 0.20, "lootTableChance": 0.15,
                 "messageChance": 0.05, "claimExpiryHours": 0, "tierWeights": [0.35, 0.8, 1.0, 1.0, 1.0],
                 "typeWeights": {"place_block": 0.4}},
    },
    "typeWeights": {"collect_item": 1.0, "mine_block": 1.0, "craft_item": 1.0, "smelt_item": 0.8, "kill_mob": 1.0,
                    "breed_animal": 0.6, "tame_animal": 0.25, "consume_item": 0.6, "place_block": 0.35,
                    "visit_dimension": 0.15},
    "hintMultipliers": {"desert": 1.3, "swamp": 1.3, "jungle": 1.4, "taiga": 1.2, "snowy": 1.3, "ocean": 1.2,
                        "beach": 1.2, "savanna": 1.2, "badlands": 1.6, "mountains": 1.3, "flower_forest": 1.4,
                        "dark_forest": 1.3, "mushroom_fields": 2.0, "lush_caves": 1.4, "dripstone_caves": 1.3,
                        "cherry_grove": 1.5, "mangrove_swamp": 1.5, "pale_garden": 1.6, "geode": 1.3,
                        "village": 1.2, "rare": 1.6, "fortress": 1.3, "bastion": 1.5, "crimson_forest": 1.2,
                        "warped_forest": 1.2, "soul_sand_valley": 1.2, "basalt_deltas": 1.2, "end_city": 1.5,
                        "outer_islands": 1.3, "mineshaft": 1.3, "outpost": 1.3, "monument": 1.6,
                        "trial_chambers": 1.5, "deep": 1.1, "bees": 1.2, "layers": 1.3, "warm_ocean": 1.4,
                        "ruined_portal": 1.4, "deep_dark": 1.6},
    "dimensionOverheadMinutes": {"minecraft:the_nether": 3.0, "minecraft:the_end": 5.0, "modded": 5.0},
    "toolLevels": {"none": 0, "wood": 0, "fishing_rod": 0, "knife": 0, "shovel": 0, "stone": 1, "shears": 1,
                   "iron": 2, "diamond": 3, "silk_touch": 3, "netherite": 4},
    "toolPenaltyPerLevel": 0.15,
    "multiObjective": {"effortFactor": [1.0, 1.0, 1.0], "rewardPremium": [1.0, 1.1, 1.2]},
    "rewards": {"itemShare": 0.75, "xpPointsPerValue": 12, "minXp": 5, "maxXp": 500, "tolerance": 0.2},
    "progression": {"netherUnlockShare": 0.25, "netherUnlockDay": 10,
                    "netherAdvancement": "minecraft:story/enter_the_nether",
                    "endUnlockShare": 0.25, "endUnlockDay": 40,
                    "endAdvancements": ["minecraft:story/enter_the_end", "minecraft:end/root"],
                    "earlyWorld": [{"maxDay": 2, "tierWeights": [1.0, 0.6, 0.15, 0.05, 0.05]},
                                   {"maxDay": 6, "tierWeights": [1.0, 1.0, 0.6, 0.5, 0.3]}]},
    "setRules": {"minDistinctTypes": 3, "maxTypeShare": 0.4, "requireQuick": True, "quickFraction": 0.3333,
                 "minPerActiveModAt": 5, "maxPerModShare": 0.5, "typeRepeatPenalty": 0.45, "themeChance": 0.85,
                 "maxAttemptsPerSlot": 40, "rangeSlack": 0.25, "minTargetFraction": 0.5},
    "calibration": {"minSamples": 5, "minMultiplier": 0.5, "maxMultiplier": 2.0, "maxStepPerCycle": 0.10},
}

TAGS = {
    "format": 1,
    "notes": "Concept -> candidate tag ids in preference order; the first tag with members on the running build wins. "
             "Conventions differ: forge:ingots/iron (Forge <=1.20.1), c:iron_ingots (older Fabric), "
             "c:ingots/iron (newer Fabric/NeoForge).",
    "concepts": {
        "logs": {"kind": "item", "candidates": ["minecraft:logs"], "name": "log", "plural": "logs"},
        "wool": {"kind": "item", "candidates": ["minecraft:wool"], "name": "wool", "plural": "wool"},
        "beds": {"kind": "item", "candidates": ["minecraft:beds"], "name": "bed", "plural": "beds"},
        "small_flowers": {"kind": "item", "candidates": ["minecraft:small_flowers"], "name": "flower",
                          "plural": "flowers"},
        "iron_ingots": {"kind": "item", "candidates": ["c:ingots/iron", "c:iron_ingots", "forge:ingots/iron"],
                        "name": "iron ingot", "plural": "iron ingots"},
        "zinc_ingots": {"kind": "item", "candidates": ["c:ingots/zinc", "c:zinc_ingots", "forge:ingots/zinc"],
                        "name": "zinc ingot", "plural": "zinc ingots"},
        "wool_carpets": {"kind": "item", "candidates": ["minecraft:wool_carpets", "minecraft:carpets"], "name": "carpet", "plural": "carpets"},
        "fishes": {"kind": "item", "candidates": ["minecraft:fishes"], "name": "fish", "plural": "fish"},
        "tomatoes": {"kind": "item", "candidates": ["c:crops/tomato", "c:tomatoes", "forge:crops/tomato"],
                     "name": "tomato", "plural": "tomatoes"},
    },
}
