"""Second batch of vanilla content (extension phase). Verified with verify_vanilla.py against the
registries of 1.18.2 ... 1.21.10 and the recipes of 1.18.2, 1.20.1, 1.21.1 and 1.21.10."""
from catalog_dsl import T, E

NE = "minecraft:the_nether"
EN = "minecraft:the_end"

MORE = [
    # ------------------------------------------------------------ deep ores & stone crafts
    E("deep_coal", "coal", 1, [T("mine_block", "minecraft:deepslate_coal_ore", 0.6, 4, 24)], tool="wood", hints=["deep"]),
    E("deep_copper", "metals", 1, [T("mine_block", "minecraft:deepslate_copper_ore", 0.4, 8, 32)], tool="stone",
      hints=["deep"], since="1.17"),
    E("deep_lapis", "gems", 2, [T("mine_block", "minecraft:deepslate_lapis_ore", 1.2, 2, 16)], tool="stone", hints=["deep"]),
    E("deep_redstone", "redstone", 2, [T("mine_block", "minecraft:deepslate_redstone_ore", 0.9, 4, 24)], tool="iron",
      hints=["deep"]),
    E("copper_blocks", "copper_works", 1, [
        T("craft_item", "minecraft:copper_block", 1.3, 1, 8, hint="Nine copper ingots."),
        T("craft_item", "minecraft:cut_copper", 1.4, 4, 16, hint="Four copper blocks make four cut copper."),
        T("place_block", "minecraft:copper_block", 1.35, 1, 8, hint="Watch it oxidize over time."),
        T("craft_item", "minecraft:copper_grate", 1.4, 4, 16, since="1.21"),
        T("craft_item", "minecraft:copper_door", 0.5, 3, 12, since="1.21"),
    ], since="1.17"),
    E("polished_stone", "stonework", 0, [
        T("craft_item", "minecraft:polished_andesite", 0.07, 16, 64),
        T("craft_item", "minecraft:polished_granite", 0.07, 16, 64),
        T("craft_item", "minecraft:polished_diorite", 0.07, 16, 64),
        T("craft_item", "minecraft:mossy_cobblestone", 0.15, 8, 48, hint="Cobblestone with vines or moss."),
        T("craft_item", "minecraft:mossy_stone_bricks", 0.2, 8, 48, hint="Stone bricks with vines or moss."),
        T("smelt_item", "minecraft:cracked_stone_bricks", 0.2, 8, 48, hint="Smelt stone bricks."),
        T("craft_item", "minecraft:stone_brick_stairs", 0.2, 8, 48),
        T("craft_item", "minecraft:smooth_stone_slab", 0.12, 12, 48, hint="Three smooth stone make six slabs."),
    ]),
    E("deepslate_masonry", "stonework", 1, [
        T("craft_item", "minecraft:polished_deepslate", 0.1, 16, 64),
        T("craft_item", "minecraft:deepslate_bricks", 0.12, 16, 64),
        T("craft_item", "minecraft:deepslate_tiles", 0.14, 16, 64),
        T("smelt_item", "minecraft:cracked_deepslate_bricks", 0.2, 8, 32),
        T("place_block", "minecraft:deepslate_tiles", 0.16, 16, 64),
    ], hints=["deep"], since="1.17"),
    E("mud_bricks", "soil", 0, [
        T("craft_item", "minecraft:packed_mud", 0.25, 8, 32, hint="Mud and wheat."),
        T("craft_item", "minecraft:mud_bricks", 0.3, 8, 32),
        T("place_block", "minecraft:mud_bricks", 0.32, 8, 32),
    ], hints=["mangrove_swamp"], since="1.19"),
    E("sandstone_crafts", "sand", 0, [
        T("craft_item", "minecraft:cut_sandstone", 0.1, 8, 48),
        T("craft_item", "minecraft:red_sandstone", 0.3, 8, 32, hints=["badlands"], hint="Four red sand."),
        T("smelt_item", "minecraft:smooth_red_sandstone", 0.35, 8, 32, hints=["badlands"]),
    ]),
    E("terracotta_art", "badlands", 0, [
        T("craft_item", "minecraft:white_terracotta", 0.5, 8, 32, hint="Terracotta around white dye."),
        T("smelt_item", "minecraft:white_glazed_terracotta", 0.6, 4, 24, hint="Smelt white terracotta."),
    ]),
    E("snow_blocks", "snow", 0, [
        T("craft_item", "minecraft:snow_block", 0.15, 8, 48, hint="Four snowballs."),
        T("place_block", "minecraft:snow_block", 0.17, 8, 48),
    ], hints=["snowy"]),
    E("clay_blocks", "soil", 0, [T("mine_block", "minecraft:clay", 0.3, 8, 32)], hints=["river"]),
    E("cobwebs", "arthropods", 1, [T("mine_block", "minecraft:cobweb", 0.5, 4, 24, hint="Cut them with a sword or shears.")],
      hints=["mineshaft"]),
    E("sculk", "deep_dark", 2, [
        T("mine_block", "minecraft:sculk", 0.2, 16, 64, hint="Move quietly: the warden listens."),
        T("mine_block", "minecraft:sculk_sensor", 1.2, 2, 8, minDifficulty="normal"),
    ], hints=["deep_dark"], since="1.19"),
    E("crying_obsidian", "obsidian", 2, [T("mine_block", "minecraft:crying_obsidian", 2.0, 2, 8, minDifficulty="normal")],
      tool="diamond", hints=["ruined_portal"]),
    E("mangrove_roots", "wood", 0, [T("mine_block", "minecraft:mangrove_roots", 0.12, 16, 48)], hints=["mangrove_swamp"],
      since="1.19"),
    E("mushroom_blocks", "mushrooms", 0, [
        T("mine_block", "minecraft:red_mushroom_block", 0.15, 16, 48),
        T("mine_block", "minecraft:brown_mushroom_block", 0.15, 16, 48),
    ], hints=["dark_forest"]),
    E("pointed_dripstone", "stone", 1, [T("collect_item", "minecraft:pointed_dripstone", 0.2, 8, 32)],
      hints=["dripstone_caves"], since="1.17"),
    # ------------------------------------------------------------ plants & flowers
    E("more_flowers", "flowers", 0, [
        T("collect_item", "minecraft:blue_orchid", 0.35, 4, 16, hints=["swamp"]),
        T("collect_item", "minecraft:allium", 0.35, 4, 16, hints=["flower_forest"]),
        T("collect_item", "minecraft:azure_bluet", 0.2, 4, 24),
        T("collect_item", "minecraft:oxeye_daisy", 0.2, 4, 24),
        T("collect_item", "minecraft:red_tulip", 0.3, 4, 16, hints=["flower_forest"]),
        T("collect_item", "minecraft:sunflower", 0.3, 4, 16, hint="Sunflower plains are full of them."),
        T("collect_item", "minecraft:lilac", 0.35, 4, 16),
        T("collect_item", "minecraft:peony", 0.35, 4, 16),
    ]),
    E("dyes", "dyes", 0, [
        T("craft_item", "minecraft:red_dye", 0.12, 8, 32, hint="From poppies, tulips or beetroot."),
        T("craft_item", "minecraft:yellow_dye", 0.12, 8, 32, hint="From dandelions or sunflowers."),
        T("craft_item", "minecraft:white_dye", 0.1, 8, 32, hint="From bone meal or lilies of the valley."),
        T("craft_item", "minecraft:blue_dye", 0.25, 4, 24, hint="From cornflowers or lapis lazuli."),
        T("craft_item", "minecraft:black_dye", 0.5, 4, 16, hint="From ink sacs or wither roses."),
        T("craft_item", "minecraft:bone_meal", 0.15, 12, 64, hint="One bone makes three bone meal."),
    ]),
    E("shears_harvest", "plants", 0, [
        T("collect_item", "minecraft:vine", 0.12, 8, 32, hints=["jungle"]),
        T("collect_item", "minecraft:seagrass", 0.1, 8, 32, hints=["ocean"]),
        T("collect_item", "minecraft:glow_lichen", 0.2, 8, 32, hints=["caves"], since="1.17"),
    ], tool="shears"),
    E("sea_pickles", "ocean", 0, [T("collect_item", "minecraft:sea_pickle", 0.4, 4, 16)], hints=["warm_ocean"]),
    E("sticks", "forestry", 0, [T("collect_item", "minecraft:stick", 0.12, 8, 32, hint="Leaves and dead bushes drop sticks.")]),
    E("beetroot_seeds", "crops", 0, [T("collect_item", "minecraft:beetroot_seeds", 0.15, 8, 32)], hints=["village"]),
    E("more_saplings", "forestry", 0, [
        T("place_block", "minecraft:jungle_sapling", 0.3, 4, 16, hints=["jungle"]),
        T("place_block", "minecraft:acacia_sapling", 0.25, 4, 16, hints=["savanna"]),
        T("place_block", "minecraft:dark_oak_sapling", 0.3, 4, 16, hints=["dark_forest"]),
        T("place_block", "minecraft:cherry_sapling", 0.35, 4, 16, hints=["cherry_grove"], since="1.20"),
    ]),
    # ------------------------------------------------------------ animals
    E("mooshrooms", "wild_animals", 0, [T("breed_animal", "minecraft:mooshroom", 5.0, 2, 3, minDifficulty="hard",
      hint="Mooshrooms breed with wheat.")], hints=["mushroom_fields", "rare"]),
    E("pandas", "wild_animals", 0, [T("breed_animal", "minecraft:panda", 5.0, 2, 3, minDifficulty="hard",
      hint="Pandas breed with bamboo near bamboo.")], hints=["jungle", "rare"]),
    E("axolotls", "wild_animals", 1, [T("breed_animal", "minecraft:axolotl", 3.5, 2, 4, minDifficulty="normal",
      hint="Axolotls breed with a bucket of tropical fish.")], hints=["lush_caves"], since="1.17"),
    E("ocelots", "wild_animals", 0, [T("breed_animal", "minecraft:ocelot", 4.0, 2, 4, minDifficulty="normal",
      hint="Ocelots breed with raw cod or salmon.")], hints=["jungle"]),
    E("striders", "nether_animals", 3, [T("breed_animal", "minecraft:strider", 3.0, 2, 4,
      hint="Striders breed with warped fungus.")], dim=NE),
    E("hoglins_farm", "nether_animals", 3, [T("breed_animal", "minecraft:hoglin", 4.0, 2, 4, minDifficulty="hard",
      hint="Hoglins breed with crimson fungus; they fight back.")], dim=NE, hints=["crimson_forest"]),
    E("rabbit_food", "wild_animals", 0, [
        T("collect_item", "minecraft:rabbit", 1.0, 2, 12, name="Raw Rabbit"),
        T("smelt_item", "minecraft:cooked_rabbit", 1.1, 2, 12, hints=["cook"]),
        T("consume_item", "minecraft:cooked_rabbit", 1.6, 1, 4),
    ], hints=["desert"]),
    E("more_meals", "cooking", 0, [
        T("consume_item", "minecraft:cooked_chicken", 1.1, 2, 6),
        T("consume_item", "minecraft:cooked_mutton", 1.2, 2, 6),
        T("consume_item", "minecraft:cooked_salmon", 2.0, 2, 4),
        T("consume_item", "minecraft:golden_apple", 10.5, 1, 1, tier=2, minDifficulty="hard",
          hint="Golden apples can be eaten any time."),
    ]),
    E("turtle_scute", "wild_animals", 0, [
        T("collect_item", "minecraft:turtle_scute", 12.0, 1, 2, alt=["minecraft:scute"], minDifficulty="hard",
          hint="Baby turtles drop a scute when they grow up."),
    ], hints=["beach"], notes="minecraft:scute was renamed to turtle_scute in 1.20.5; both ids are tried."),
    # ------------------------------------------------------------ monsters & drops
    E("silverfish", "arthropods", 1, [T("kill_mob", "minecraft:silverfish", 1.5, 4, 12, minDifficulty="normal",
      hint="They hide in infested stone in mountains and strongholds.")], hints=["mountains"]),
    E("phantoms", "undead", 1, [
        T("kill_mob", "minecraft:phantom", 3.0, 2, 6, minDifficulty="hard"),
        T("collect_item", "minecraft:phantom_membrane", 3.5, 1, 4, minDifficulty="hard"),
    ], hints=["night"], exclusions=["hint: phantoms only spawn after three nights without sleep"]),
    E("piglin_hunt", "nether_mobs", 3, [T("kill_mob", "minecraft:piglin", 1.4, 4, 12,
      hint="Piglins attack players without gold armor.")], dim=NE, hints=["crimson_forest"]),
    E("prismarine", "ocean", 2, [
        T("collect_item", "minecraft:prismarine_crystals", 2.0, 2, 12, minDifficulty="normal"),
        T("mine_block", "minecraft:prismarine", 0.35, 8, 32, minDifficulty="normal"),
    ], hints=["monument"], tool="iron"),
    E("gold_nuggets", "nether_ores", 3, [T("collect_item", "minecraft:gold_nugget", 0.1, 16, 64,
      hint="Nether gold ore drops gold nuggets.")], dim=NE),
    E("shroomlight", "nether_plants", 3, [T("collect_item", "minecraft:shroomlight", 0.8, 4, 16)], dim=NE,
      hints=["crimson_forest"]),
    E("nether_wart_blocks", "nether_plants", 3, [
        T("mine_block", "minecraft:nether_wart_block", 0.15, 16, 48, hints=["crimson_forest"]),
        T("mine_block", "minecraft:warped_wart_block", 0.15, 16, 48, hints=["warped_forest"]),
        T("mine_block", "minecraft:crimson_nylium", 0.08, 16, 64, hints=["crimson_forest"]),
    ], dim=NE),
    E("magma_glow", "nether_blocks", 3, [
        T("mine_block", "minecraft:magma_block", 0.12, 8, 32),
        T("mine_block", "minecraft:glowstone", 0.3, 8, 32),
        T("mine_block", "minecraft:bone_block", 1.0, 2, 8, hints=["soul_sand_valley"], hint="Fossils in soul sand valleys."),
    ], dim=NE),
    E("nether_masonry", "nether_crafts", 3, [
        T("craft_item", "minecraft:nether_bricks", 0.35, 8, 32, hint="Four Nether brick items."),
        T("craft_item", "minecraft:red_nether_bricks", 1.0, 4, 16, hint="Nether bricks and Nether wart."),
        T("craft_item", "minecraft:quartz_block", 1.2, 4, 16, hint="Four Nether quartz."),
        T("smelt_item", "minecraft:smooth_quartz", 1.3, 4, 16),
        T("craft_item", "minecraft:polished_blackstone", 0.08, 16, 64, hints=["basalt_deltas"]),
        T("craft_item", "minecraft:blaze_powder", 0.8, 4, 16, hint="One blaze rod makes two powder."),
        T("craft_item", "minecraft:magma_cream", 1.6, 2, 8),
    ], dim=NE),
    E("chorus_plants", "end_plants", 4, [T("mine_block", "minecraft:chorus_plant", 0.1, 16, 64)], dim=EN,
      hints=["outer_islands"]),
    # ------------------------------------------------------------ tools, armor, workstations
    E("leather_armor", "leather_armor", 0, [
        T("craft_item", "minecraft:leather_helmet", 2.2, 1, 1),
        T("craft_item", "minecraft:leather_chestplate", 3.4, 1, 1),
        T("craft_item", "minecraft:leather_leggings", 3.0, 1, 1),
        T("craft_item", "minecraft:leather_boots", 1.8, 1, 1),
    ], hints=["plains"]),
    E("diamond_armor", "diamond_gear", 2, [
        T("craft_item", "minecraft:diamond_helmet", 25.0, 1, 1, minDifficulty="hard"),
        T("craft_item", "minecraft:diamond_boots", 20.0, 1, 1, minDifficulty="hard"),
    ], weight=0.5),
    E("workstations", "workstations", 0, [
        T("craft_item", "minecraft:cartography_table", 0.6, 1, 3),
        T("craft_item", "minecraft:fletching_table", 0.6, 1, 3),
        T("craft_item", "minecraft:loom", 0.7, 1, 3),
        T("craft_item", "minecraft:grindstone", 0.6, 1, 3),
        T("craft_item", "minecraft:smithing_table", 1.3, 1, 2, tier=1),
        T("craft_item", "minecraft:stonecutter", 0.8, 1, 3, tier=1),
        T("craft_item", "minecraft:cauldron", 3.9, 1, 1, tier=1),
        T("craft_item", "minecraft:lectern", 5.0, 1, 1),
        T("craft_item", "minecraft:anvil", 17.0, 1, 1, tier=1, minDifficulty="hard", hint="31 iron ingots."),
        T("craft_item", "minecraft:enchanting_table", 16.0, 1, 1, tier=2, minDifficulty="hard"),
        T("craft_item", "minecraft:brewing_stand", 4.0, 1, 2, tier=3, hint="Needs a blaze rod from a Nether fortress."),
        T("craft_item", "minecraft:jukebox", 5.5, 1, 1, tier=2, minDifficulty="normal"),
    ]),
    E("redstone_parts", "redstone", 2, [
        T("craft_item", "minecraft:redstone_torch", 0.3, 4, 16),
        T("craft_item", "minecraft:repeater", 1.0, 2, 8),
        T("craft_item", "minecraft:dispenser", 1.6, 1, 4),
        T("craft_item", "minecraft:dropper", 0.6, 2, 6),
        T("craft_item", "minecraft:note_block", 1.0, 2, 6),
        T("craft_item", "minecraft:target", 2.0, 1, 4),
        T("craft_item", "minecraft:tripwire_hook", 0.8, 2, 8, tier=1),
    ]),
    E("transport", "transport", 0, [
        T("craft_item", "minecraft:oak_boat", 0.3, 1, 4),
        T("craft_item", "minecraft:lead", 1.8, 1, 4, tier=1, hint="String and a slimeball."),
        T("craft_item", "minecraft:powered_rail", 1.6, 6, 18, tier=2, hint="Gold ingots, a stick and redstone."),
        T("craft_item", "minecraft:detector_rail", 1.0, 6, 12, tier=1),
    ]),
    E("gear_misc", "archery", 1, [
        T("craft_item", "minecraft:crossbow", 2.2, 1, 2),
        T("craft_item", "minecraft:flint_and_steel", 0.8, 1, 3),
        T("craft_item", "minecraft:spectral_arrow", 1.2, 2, 8, tier=3),
    ]),
    E("potion_prep", "brewing", 1, [
        T("craft_item", "minecraft:fermented_spider_eye", 1.8, 1, 8, tier=0, hint="Spider eye, sugar and a brown mushroom."),
        T("craft_item", "minecraft:glistering_melon_slice", 1.5, 1, 8, tier=2),
        T("craft_item", "minecraft:glass_bottle", 0.12, 6, 24, tier=0),
    ]),
    E("maps", "exploration", 2, [T("craft_item", "minecraft:map", 3.5, 1, 2, minDifficulty="normal")]),
    E("storage", "woodwork", 0, [
        T("craft_item", "minecraft:trapped_chest", 0.6, 2, 8),
        T("craft_item", "minecraft:ender_chest", 9.0, 1, 1, tier=3, minDifficulty="hard"),
        T("place_block", "minecraft:barrel", 0.4, 2, 12),
    ]),
    E("decor_more", "decor", 0, [
        T("craft_item", "minecraft:white_carpet", 0.15, 6, 48, tag="wool_carpets", hint="Two wool make three carpets."),
        T("place_block", "minecraft:white_carpet", 0.18, 6, 48),
        T("craft_item", "minecraft:white_banner", 1.6, 1, 4),
        T("craft_item", "minecraft:glow_item_frame", 1.4, 2, 6, tier=1),
        T("craft_item", "minecraft:white_stained_glass", 0.2, 8, 32),
        T("craft_item", "minecraft:beehive", 3.6, 1, 2, hints=["bees"]),
        T("craft_item", "minecraft:chiseled_bookshelf", 0.4, 1, 6, since="1.20"),
        T("craft_item", "minecraft:decorated_pot", 0.5, 1, 6, since="1.20"),
        T("place_block", "minecraft:oak_fence", 0.12, 8, 48),
        T("craft_item", "minecraft:oak_fence", 0.1, 9, 48),
    ]),
    E("food_crafts", "baking", 0, [
        T("craft_item", "minecraft:mushroom_stew", 1.0, 1, 6, hints=["dark_forest"]),
        T("craft_item", "minecraft:beetroot_soup", 1.8, 1, 4),
        T("craft_item", "minecraft:rabbit_stew", 3.0, 1, 3, hints=["desert"]),
        T("craft_item", "minecraft:sugar", 0.1, 8, 64, hint="Crafted from sugar cane."),
        T("craft_item", "minecraft:honey_block", 4.5, 1, 2, hints=["bees"]),
        T("craft_item", "minecraft:dried_kelp_block", 1.0, 2, 8, hints=["ocean"]),
    ]),
    E("sponge", "ocean", 2, [T("smelt_item", "minecraft:sponge", 4.0, 1, 4, minDifficulty="hard",
      hint="Dry wet sponges from ocean monuments.")], hints=["monument"]),
    E("lighting_more", "lighting", 1, [
        T("craft_item", "minecraft:soul_torch", 0.12, 8, 48, tier=3, dimension=NE),
        T("craft_item", "minecraft:soul_lantern", 1.0, 2, 8, tier=3, dimension=NE),
        T("place_block", "minecraft:campfire", 0.55, 2, 8, tier=0),
        T("craft_item", "minecraft:sea_lantern", 5.5, 1, 4, tier=2, minDifficulty="hard", hints=["monument"]),
    ]),
    E("glass_more", "glass", 0, [T("place_block", "minecraft:glass_pane", 0.06, 16, 64)]),
    E("chain_place", "iron_works", 1, [T("place_block", "minecraft:iron_chain", 0.75, 4, 16, alt=["minecraft:chain"])]),
    E("blocks_of", "storage_blocks", 1, [
        T("craft_item", "minecraft:iron_block", 5.0, 1, 3, hint="Nine iron ingots."),
        T("craft_item", "minecraft:lapis_block", 1.8, 1, 6, tier=2),
        T("craft_item", "minecraft:redstone_block", 1.8, 1, 6, tier=2),
        T("craft_item", "minecraft:coal_block", 2.3, 1, 6, tier=0),
    ]),
    # ------------------------------------------------------------ 0.3.3: stonecutter, enchanting, use, brewing
    E("stonecutting", "stonework", 0, [
        T("craft_item", "minecraft:stone_brick_stairs", 0.12, 16, 64, hint="A stonecutter makes them one for one."),
        T("craft_item", "minecraft:chiseled_stone_bricks", 0.14, 8, 48, hint="Use a stonecutter on stone."),
        T("craft_item", "minecraft:cut_copper", 0.3, 8, 32, tier=1, tool="stone", since="1.17",
          hint="Cut copper blocks on a stonecutter."),
    ], tool="wood", notes="The stonecutter counts as crafting since mod 0.3.3."),
    E("enchanting", "enchanting", 2, [
        T("enchant_item", "minecraft:enchanted_book", 3.5, 1, 5, name="Book", plural="Books", stack=1,
          hint="Enchant books on an enchanting table; any enchantment counts."),
        T("enchant_item", "minecraft:iron_pickaxe", 3.0, 1, 3, stack=1, hint="Any enchantment counts."),
        T("enchant_item", "minecraft:iron_sword", 3.0, 1, 3, stack=1, hint="Any enchantment counts."),
        T("enchant_item", "minecraft:bow", 3.5, 1, 3, stack=1, hint="Any enchantment counts."),
        T("enchant_item", "minecraft:diamond_sword", 6.0, 1, 2, stack=1, minDifficulty="hard",
          hint="Any enchantment counts."),
    ], tool="iron", weight=2.5, notes="The target is the enchanted result, so books are enchanted_book. Anvils do not count."),
    E("use_items", "use_items", 0, [
        T("use_item", "minecraft:snowball", 0.08, 16, 64, hints=["snowy", "throw"], stack=16,
          hint="Shovel snow and throw the snowballs."),
        T("use_item", "minecraft:egg", 0.6, 4, 16, hints=["farm", "throw"], stack=16, hint="Chickens lay eggs."),
        T("use_item", "minecraft:ender_pearl", 2.5, 2, 8, tier=2, hints=["night", "throw"], stack=16,
          hint="Endermen drop ender pearls."),
        T("use_item", "minecraft:bone_meal", 0.15, 8, 48, hints=["night"], hint="Use bone meal on crops or grass."),
        T("use_item", "minecraft:firework_rocket", 0.5, 3, 16, tier=1, hints=["launch"],
          hint="Craft rockets from paper and gunpowder."),
    ], weight=2.5, notes="use_item counts the vanilla Times Used statistic: only uses that do something."),
    E("potions", "brewing", 3, [
        T("consume_item", "minecraft:potion", 4.0, 1, 3, potion="minecraft:swiftness", name="Potion of Swiftness",
          plural="Potions of Swiftness", stack=1, hints=["drink"], hint="Brew an Awkward Potion with sugar."),
        T("consume_item", "minecraft:potion", 4.0, 1, 3, potion="minecraft:night_vision", name="Potion of Night Vision",
          plural="Potions of Night Vision", stack=1, hints=["drink"], hint="Brew an Awkward Potion with a golden carrot."),
        T("consume_item", "minecraft:potion", 4.5, 1, 3, potion="minecraft:fire_resistance",
          name="Potion of Fire Resistance", plural="Potions of Fire Resistance", stack=1, hints=["drink"],
          hint="Brew an Awkward Potion with magma cream."),
        T("consume_item", "minecraft:potion", 4.5, 1, 3, potion="minecraft:strength", name="Potion of Strength",
          plural="Potions of Strength", stack=1, hints=["drink"], hint="Brew an Awkward Potion with blaze powder."),
        T("consume_item", "minecraft:potion", 5.0, 1, 2, potion="minecraft:water_breathing",
          name="Potion of Water Breathing", plural="Potions of Water Breathing", stack=1, hints=["ocean", "drink"],
          hint="Brew an Awkward Potion with a pufferfish."),
    ], requires=["nether"], weight=2.0, notes="Needs a brewing stand (blaze rod) and nether wart."),
]
