package com.erikedits.justquests.generator.v2;

import com.erikedits.justquests.generator.v2.api.Difficulty;
import com.erikedits.justquests.generator.v2.internal.Generation;
import com.erikedits.justquests.generator.v2.internal.catalog.Catalog;
import com.erikedits.justquests.generator.v2.internal.catalog.EntryDef;
import com.erikedits.justquests.generator.v2.internal.catalog.ProfileDef;
import com.erikedits.justquests.generator.v2.internal.catalog.TargetDef;
import com.erikedits.justquests.generator.v2.internal.catalog.ThemeDef;
import com.erikedits.justquests.generator.v2.internal.gen.Candidate;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.EnumMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

/**
 * Writes {@code samples/catalog-report.md}: every catalog target with its effort, count range, the
 * minutes it spans and the difficulties it can appear on (world with Nether and End unlocked, both
 * mods loaded, Minecraft 1.21.1). A tuning aid for the test phase. Run with {@code ./gradlew catalogReport}.
 */
public final class CatalogReport {
    private CatalogReport() {
    }

    public static void main(String[] args) throws IOException {
        Path out = Path.of(args.length > 0 ? args[0] : "samples/catalog-report.md");
        FakeHost host = new FakeHost().withMods("farmersdelight", "create", "mekanism", "twilightforest", "botania");
        host.content.dimensions.add("twilightforest:twilight_forest");
        Catalog catalog = TestSupport.catalog();
        Map<Difficulty, Map<String, Candidate>> pools = new EnumMap<>(Difficulty.class);
        for (Difficulty d : Difficulty.values()) {
            Generation.Result r = Generation.run(catalog, host, TestSupport.config(d, 1), TestSupport.unlockedProgression(host),
                Map.of(), Set.of(), List.of(), 1, 1L, 1L, 0);
            Map<String, Candidate> m = new TreeMap<>();
            for (Candidate c : r.pool().candidates()) {
                m.put(key(c.entry(), c.def()), c);
            }
            pools.put(d, m);
        }
        StringBuilder sb = new StringBuilder();
        sb.append("# Catalog report\n\n");
        sb.append("Generated by `./gradlew catalogReport` from the bundled data. Assumptions: Minecraft 1.21.1, ")
            .append("all five mod profiles loaded (the Twilight Forest dimension unlocked), ")
            .append("every id exists, every host answer UNKNOWN, game day 100, Nether ")
            .append("and End unlocked. *Minutes* = count × effort × modifiers (+ travel overhead) at the minimum and ")
            .append("maximum count. *E/N/H* = the target can appear on Easy / Normal / Hard (tier cap, minimum ")
            .append("difficulty and minute range all pass).\n\n");
        Map<String, int[]> perType = new TreeMap<>();
        StringBuilder rows = new StringBuilder();
        for (ProfileDef p : catalog.profiles) {
            rows.append("\n## Profile `").append(p.id()).append("` — ").append(p.name()).append("\n\n");
            rows.append("| Entry | Family | Type | Target | Tier | Effort | Count | Minutes | E | N | H | Hints |\n");
            rows.append("|---|---|---|---|---|---|---|---|---|---|---|---|\n");
            for (EntryDef e : p.entries()) {
                for (TargetDef t : e.targets()) {
                    String k = key(e, t);
                    Candidate any = null;
                    StringBuilder flags = new StringBuilder();
                    for (Difficulty d : Difficulty.values()) {
                        Candidate c = pools.get(d).get(k);
                        flags.append(" | ").append(c != null ? "✓" : "·");
                        if (c != null && any == null) {
                            any = c;
                        }
                    }
                    int[] counts = perType.computeIfAbsent(p.id() + " " + t.type().shortName(), x -> new int[2]);
                    counts[0]++;
                    if (any != null) {
                        counts[1]++;
                    }
                    String minutes = any == null ? "—"
                        : String.format(Locale.ROOT, "%.1f–%.1f", any.minMinutes(), any.maxMinutes());
                    int tier = t.tier() >= 0 ? t.tier() : e.tier();
                    String target = t.id() != null ? t.id() : "#" + t.tagConcept();
                    if (t.tagConcept() != null) {
                        target += " (tag " + t.tagConcept() + ")";
                    }
                    rows.append("| ").append(e.key()).append(" | ").append(e.family()).append(" | ")
                        .append(t.type().shortName()).append(" | `").append(target).append("` | ").append(tier)
                        .append(" | ").append(String.format(Locale.ROOT, "%.2f", t.effort())).append(" | ")
                        .append(t.type().counted() ? t.min() + "–" + t.max() : "—").append(" | ").append(minutes)
                        .append(flags).append(" | ").append(String.join(", ", any != null ? any.hints() : e.hints()))
                        .append(" |\n");
                }
            }
        }
        sb.append("## Summary\n\n| Profile / type | Targets | Usable here |\n|---|---|---|\n");
        perType.forEach((k, v) -> sb.append("| ").append(k).append(" | ").append(v[0]).append(" | ").append(v[1]).append(" |\n"));
        sb.append("\nPool size per difficulty: ");
        for (Difficulty d : Difficulty.values()) {
            sb.append(d).append(' ').append(pools.get(d).size()).append("  ");
        }
        sb.append("\n\nThemes: ");
        Map<String, Integer> themes = new TreeMap<>();
        for (ThemeDef t : catalog.themes) {
            themes.merge(t.profile(), 1, Integer::sum);
        }
        sb.append(themes).append('\n');
        sb.append(rows);
        Files.createDirectories(out.toAbsolutePath().getParent());
        Files.writeString(out, sb.toString(), StandardCharsets.UTF_8);
        System.out.println("wrote " + out);
    }

    private static String key(EntryDef e, TargetDef t) {
        return e.profile() + ":" + e.key() + ":" + t.type().shortName() + ":" + (t.id() != null ? t.id() : t.tagConcept());
    }
}
